apiVersion: v1
kind: Service
metadata:
  name: hello-active
  namespace: production
spec:
  selector:
    app: demo-rollout
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP
  type: ClusterIP

