# deployment-definition.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-container
        image: hashicorp/http-echo:latest
        args: ["-text", "Welcome to Devops agian!!!"]

